---
- name: Download Flume 
  get_url: url=http://apache.claz.org/flume/{{flume_version}}/apache-flume-{{flume_version}}-bin.tar.gz dest=/home/ec2-user/flume.tar.gz checksum="{{ flume_checksum }}"

- name: Extract Flume archive
  command: chdir=/usr/local/ /bin/tar xvf /home/ec2-user/flume.tar.gz 

- name: Clean up Flume tar file
  file:
      path: /home/ec2-user/flume.tar.gz
      state: absent

- name: Rename Flume directory
  command: mv /usr/local/apache-flume-{{flume_version}}-bin /usr/local/flume

- name: Add Flume to PATH (only if not already added)
  shell: fgrep flume /home/ec2-user/.bashrc || echo 'export PATH=$PATH:/usr/local/flume/bin' >> /home/ec2-user/.bashrc && source /home/ec2-user/.bashrc
