---
- name: Create directory for scripts
  file: path=/home/ec2-user/scripts state=directory

- name: Set host name
  command: hostname {{host_name}}

- name: Install Java JDK 1.8
  yum: name=java-1.8.0 state=present

- name: Remove old JDK
  yum: name=java-1.7.0-openjdk state=removed

- name: Enable EPEL repo
  command: sudo yum-config-manager --enable epel





